version: "2.0"

services:
    # node-red
    node-red:
        extends:
            file: service-types.yml
            service: node-red
        build: ./
        restart: always
        networks:
            app:
                aliases:
                    - node-red
        ports:
            - '80:80'
        links:
            - views
    views:
        extends:
            file: service-types.yml
            service: microservice
        build: ./components/Views
        networks:
            app:
                aliases:
                    - views        
        restart: always        
        expose:
            - '10201'

networks:
    app: {}