version: "2.0"

services:
    # flows data-only container
    flows:
        image: "node:argon"
        volumeas:
            - /usr/src/flows
    # microservices
    # users
#    users:
#        extends:
#            file: "service-types.yml"
#            service: "microservice"
#        build: ./components/users
#        ports: 
#            - "1011:1000"

#    articles:
#        extends:
#            file: "service-types.yml"
#            service: "microservice"
#        build: ./components/articles
#        ports: 
#            - "1012:1000"

#    categories:
#        extends:
#            file: "service-types.yml"
#            service: "microservice"
#        build: ./components/categories
#        ports: 
#            - "1013:1000"
#
#    public:
#        extends:
#            file: "service-types.yml"
#            service: "microservice"
#        build: ./components/public
#        ports: 
#            - "1014:1000"

    # node-red
    node-red:
        extends:
            file: "service-types.yml"
            service: "node-red"
        build: ./
        volumes_from:
            - flows
        ports:
            - "80:80"
        links:
            - users
            - articles
            - public
            - categories
    # nginx
#    nginx:
#        build: ./nginx
#        ports:
#            - "80:80"
#    #phabricator-related Services
#    # database
#    database:
#        build: ./docker-phabricator/database
#        
#    #phabricator
#    phab:
#        build: ./docker-phabricator
#        ports:
#            - "8081:80"