version: "2.0"

services:
    # node-red
    node-red:
        extends:
            file: "service-types.yml"
            service: "node-red"
        build: ./
        volumes:
            - /usr/src/flows
        ports:
            - "80:80"