version: "2.0"

services:
    # flows data-only container
    flows:
        image: "node:argon"
        volumeas:
            - /usr/src/flows
    # node-red
    node-red:
        extends:
            file: "service-types.yml"
            service: "node-red"
        build: ./
        volumes_from:
            - flows
        ports:
            - "80:80"
#        links:
#            - users
#            - articles
#            - public
#            - categories